### ISSUE TITLE
Recommend open source knowledge base software

### ISSUE THREAD

**Issue by kgodey** [creativecommons/faq#31]
_This is an Outreachy contribution task. Multiple people may complete this task, it will not be closed until the Outreachy winter 2019 contribution period ends._

---
Research open source knowledge base software and write up a set of recommendations about what you think CC should be using. Post your recommendations here.

**Comment by mchesler613** [comment]
Does CC have a budget in mind? That will help narrow down the choices.  :)

**Comment by kgodey** [comment]
We would prefer something free and open source than we can self-host. Something that integrates into WordPress would work too since the main CC website is built in WordPress.

**Comment by mchesler613** [comment]
Hi @kgodey, I have created a Knowledge Base software powered by phpMyFAQ on my personal domain and installed several FAQs under different headings. Please take a look, http://moriahweb.com/cc. The site is searchable and I have also edited the FAQ headings using AP-style titling here, https://capitalizemytitle.com/#. Please check it out and let me know if you want more FAQs in there. This site is not backed up.

This reply is for issue https://github.com/creativecommons/faq/issues/34

**Comment by kgodey** [comment]
@mmoreshead @ericsteuer

**Comment by mchesler613** [comment]
@kgodey @mmoreshead @ericsteuer I installed a Wordpress site and am experimenting with a few free  Knowledge Base plugins and will demo what I have soon.

**Comment by cthomas88** [comment]
I have done some extensive research over the last few days, looking into different knowledge based softwares, and educating myself on what they are and how they can be used, which I found interesting. I have found three that stood out for me, two that are free and one that is not to give a wide spectrum of what is on offer for Creative Commons. I hope it is of some use to you.

**_Documize_** - Documize is free and open source, and developers are expected and encouraged to explore its source code. It has a beautifully seamless website of its own with great documentation and a good community. 
Here is their GitHub repo: https://github.com/documize/community
Here is their website: https://www.documize.com/

_**phpMyFAQ**_ - Obviously this will integrate well with WordPress due to both bring written in PHP. phpMyFAQ is a mobile-friendly, feature-rich, scalable open source FAQ software – written in PHP, obviously. It’s completely free and open source under the Mozilla Public License Version 2.0. Developers are encouraged to contribute patches or features to the codebase.
Here is their GitHub repo: https://github.com/thorsten/phpMyFAQ
Here is their website: https://www.phpmyfaq.de/

**_exo Platform_** - Whilst not free, this is inexpensive and the costs come with the peace of mind of a regularly updated software that is run by professionals and is still open source. This software can be self-hosted and is popular among huge corporate businesses with well known names, such as HSBC and UCLA. 
Here is their GitHub Repo - https://github.com/exoplatform
Here is their website - https://www.exoplatform.com/

**Comment by mchesler613** [comment]
@cthomas88  phpMyFAQ, although is php-based, does not integrate with Wordpress.  There is no plugin available for it for Wordpress.  I  have one already running here: http://moriahweb.com/cc. It is quite solid and easy to use.  Please take a look.

**Comment by mbengtanyi** [comment]
In addition to the other open source knowledge base software already listed here like Documize, eXo, and the popular phpMyFAQ, I also came across OpenKM.
 I have not used it yet, but from my research, it integrates with Wordpress. 
OpenKM apparently also comes with simplicity and ease of maintenance over time. Although [here](https://www.betterbuys.com/dms/reviews/openkm/) it is said that the community version has very basic features as compared to the cloud or professional versions.
[Link to their github](https://github.com/openkm/document-management-system) and [webpage](https://www.openkm.us/en/knowledge-management-system.html).

**Comment by kgodey** [comment]
@mchesler613 @cthomas88 @mbengtanyi thank you for your research! I don't have a lot of specific feedback but all this research seems like it will be very useful for whatever course of action you choose to recommend in your final application.

A couple of general things:
(1) We definitely want something that's as easy to manage for non-technical folks as possible as that's as geared towards FAQs as possible. I am somewhat familiar with Documize and that's a more generic wiki solution AFAIK – setting up FAQs with it seems like it would be more work than using a more customized FAQ solution. I might be missing something, though.
(2) You've done an good job of identifying pros/cons/differences between various software solutions. I encourage you to ask questions about requirements (especially while writing your application / internship plan so that you can decide on which software would be best for CC's uses.

**Comment by mbengtanyi** [comment]
> @mchesler613 @cthomas88 @mbengtanyi thank you for your research! I don't have a lot of specific feedback but all this research seems like it will be very useful for whatever course of action you choose to recommend in your final application.
> 
> A couple of general things:
> (1) We definitely want something that's as easy to manage for non-technical folks as possible as that's as geared towards FAQs as possible. I am somewhat familiar with Documize and that's a more generic wiki solution AFAIK – setting up FAQs with it seems like it would be more work than using a more customized FAQ solution. I might be missing something, though.
> (2) You've done an good job of identifying pros/cons/differences between various software solutions. I encourage you to ask questions about requirements (especially while writing your application / internship plan so that you can decide on which software would be best for CC's uses.

Thanks for the feedback.

**Comment by ericsteuer** [comment]
Looks good. Looking forward to seeing your final application. Thanks.

**Comment by BrElio** [comment]
Hi there!
I am the lead developer of [BasePress Knowledge Base](https://codesavory.com/) which was mentioned by @mchesler613 as an option for CC's website.
If you are interested in using our knowledge base plugin I'll be more than happy to help customising the look to fit CC's website.
If you have anything you would like to ask please don't hesitate to [contact us](https://codesavory.com/contact-us/)!

**Comment by kgodey** [comment]
thank you @BrElio! We haven't decided which software to use yet, but we'll definitely be in touch as we do so.

**Comment by kgodey** [comment]
Since the Outreachy application period is over, I'm going to close this issue.
