### ISSUE TITLE
Identify instances of excellent FAQs

### ISSUE THREAD

**Issue by kgodey** [creativecommons/faq#32]
_This is an Outreachy contribution task. Multiple people may complete this task, it will not be closed until the Outreachy winter 2019 contribution period ends._

---
Identify ten instances of excellent FAQs that exist on other organizations’ or companies’ websites. Post your research here.

**Comment by cthomas88** [comment]
1. https://pythonpro.co.uk/Services - This website was created by me, using a simple click and drop method with Bootstrap

2. https://help.twitter.com/en - Twitter has a great FAQ section, with image manipulation as you scroll down the page

3. https://support.google.com/youtube/?hl=en-GB#topic=9257498 - YouTube has an FAQ similar to the Python Pro page, with an accordion style Answer section

4. https://www.mcdonalds.com/gb/en-gb/help/faq.html - McDonalds has a good idea, however I would myself change a few things here, a grid system is easy to look at if incorporated into your own CC website. 

5. https://faq.whatsapp.com/ - WhatsApp has a great colour scheme that is attractive, and sections their questions under main headings for ease of use.

6. https://www.microsoft.com/en-gb/software-download/faq - Microsoft are the third instance here that uses an accordion type FAQ section, which I believe is popular and modern and allows the user to choose which areas they would like displayed on the page.

7. https://www.ucas.com/undergraduate/applying-university/frequently-asked-questions - UCAS, the university and education website also uses accordion (I'm seeing a pattern develop here!) which is stylish and smooth, with a rotating arrow icon.

8. https://www.nintendo.com/switch/online-service/faq/ - Nintendo has a similar accordion FAQ section however I would myself implement a smooth drop down instead of the sudden appearance of the Answer section.

9. https://faq.buffer.com/ - Buffer groups their questions into categories and displays them behind cards. Giving the client the ability to choose which subject matter they wish to display on the screen is effective and attractive. 

10. https://aws.amazon.com/faqs/ - Amazon Web Services has a page that is not too dissimilar to the current CC FAQ page, however it is more organised and flows better. Something to consider. 


I am Carlie, full stack developer from the UK and Outreachy intern. I would love to be considered for reorganising your FAQ page into something that is more attractive and easier for the client to navigate.

**Comment by mmoreshead** [comment]
Hey @cthomas88 - some of these are really nice, I especially like the WhatsApp one! One important aspect of CC's FAQ is the ability to point to one Q and share the link so some of the accordion ones like Nintendo look cool but we likely need a bit more functionality. 

A lot of the folks who come to our FAQ don't actually know what their question is (or the question can be asked in many ways) and often the questions fall into multiple categories so the type-ahead in the header of the WhatsApp model is really attractive to me too.

Thanks for this list!

**Comment by tyanastone** [comment]
1. [TUI](https://www.tui.co.uk/destinations/faq): I really like the grid layout of this FAQ page along with being able to click on the individual questions under each category. I like the search function as well I typed in "Book a flight" and the results were a list of common questions pertaining to booking a flight. 

2. [Fat Face](https://us.fatface.com/help-center/frequently-asked-questions.html): I really like the design & simplicity of this FAQ page, I'm not sure why but I prefer the plus and minus for drop downs instead of the down pointing arrow. I also like the animation with the transition of the plus going to the minus when you click on it. 

3. [Pinterest](https://help.pinterest.com/en): I like how everything here is all one page and side by side. I like the hover effect with the color change on each topic as well. When you click "See More" from each category, it shows even more topics. 

4. [Pretty Little Thing](https://www.prettylittlething.com/faq): I think this FAQ page is visually appealing. I like the grid layout with the icons and separate categories, there's also a hover effect as well. Once you click on the category you get the plus sign animation drop down style with the questions. I like that the grid from the previous page is also to the side so that I don't have to navigate back just to get to the original FAQ page. Being able to jump to a different category from where I currently am is a good addition. 

5. [Zappos](https://www.zappos.com/general-questions): Although this one is quite simple, I do like that it's easy to use for most visitors. When you click on the question it jumps down to the question at the bottom. Seems like a simple HTML anchor method here. 

6. [Dropbox](https://help.dropbox.com/): I like the idea of having the top articles shown first. As you scroll down you see the different categories, and at the bottom there's even a discussion forum, which I think is a great idea! 

7. [Adobe Creative Cloud](https://helpx.adobe.com/creative-cloud/faq.html): Adobe creative cloud is quite simple too, but I like the idea of clicking on the topic, and instead of opening a new tab or going to a different page, it jumps to the question at the bottom and includes a drop down. 

8. [Ancestry DNA](https://support.ancestry.com/s/): I like the search bar and layout of the page. I also like the icons at the bottom and that when you click on them it takes you to more topics to answer any questions you may have. 

9. [Pepper](https://www.wearpepper.com/pages/support): I think this style is a pretty neat idea. The categories are at the top, and when you click a topic it jumps to that bubble on the page. It's visually pleasing. Probably wouldn't work very well for a site with a lot of questions though. 

10. [Cards Against Humanity](https://store.cardsagainsthumanity.com/faq.html): I'm not a fan of the layout of this FAQ page but I wanted to add it to point out the actual questions and answers. They are funny and keeps you on the page, I actually want to read every question and answer. I like the use of humor to keep me engaged.

**Comment by mmoreshead** [comment]
Hi @tyanastone !  Thanks for these - a few of these are a lot like our current FAQ's (Zappos, for instance). See my comments from yesterday for some suggestions and do take a look at our own FAQ to see what we're already doing if you haven't already https://creativecommons.org/faq/

**Comment by kryptosjay-code** [comment]
1.    https://faq.whatsapp.com/ - Whatsapp has a great theme and a nice color combination, which makes the site elegant to behold and they categories their questions under a simple main heading which makes it easier to use, then the How can we help you? Title is lovely because once you open the page you already know what it is for. The search button is more like an icing to the page
2.    https://help.twitter.com/en - Twitter has a great FAQ section, with the sidebar container containing the major questions the subheadings and then the  scroll to the top button although the search bar is not that visible it is still a good page to work with
3.   https://www.shopify.com.ng/faq - Shopify has a great content and the grouping in sections is really nice but the heading will need a bit of a change , a new user in the site might get a bit confuse at first visit the FAQ page, but the color combination is lovely and the sidebar scrolling down with the other part of the page is lovely.
4.   https://www.microsoft.com/en-gb/software-download/faq - Microsoft uses stacked methods with links this type of FAQ section is common to web developers because it allows a user to choose the area they need clarification on but it also takes the user out of the context of the page to an entirely different page, which is if there are any other questions it will skip their mind by the time they decide to get back to the FAQ page
5.    https://www.zappos.com/general-questions - Zappos FAQ page is really simple and straight to the point just like the CC FAQ page but it needs a touch of color but the search bar makes it easier to navigate on a bit, it needs a little brushing up.
6.    https://www.worldfirst.com/en-fr/support/faq/ - Worldfirst FAQ page is a lovely page to behold, the heading makes it straight to the point the picture tabs, the drop-down tabs,  just makes it easier to use even for a first-timer and the color combination is superb, it makes the navigation very easy,
7.   https://support.google.com/youtube/?hl=en#topic= - like this FAQ page is lovely to behold although it doesn't have much, the page has its speck.
8.   https://www.bankofamerica.com/help/overview/ - Bank of America is one of my favorites FAQ page the theme, the color combination, the sectioning and the drop-down tabs the navigation efficiency of the site.
9.   https://www.gtbank.com/help-centre/quick-guides - this is a nice template  and great navigation page 
10.  https://en.wikipedia.org/wiki/Wikipedia:FAQ - this is an organized site I specifically like the sidebar and the container and the fact that each tab doesn't necessarily need to take you out of the page but scroll down the particular tab.

My name is Ugwuanyi Jacinta a web developer from Nigeria and also an Outreachy applicant, I would love to be considered for restructuring of the CC FAQ page into a more user-friendly and navigable page .


@kgodey @mmoreshead @tyanastone @robmyers

**Comment by tyanastone** [comment]
@mmoreshead Thanks, would you like me to revise some of my suggestions with different websites?

**Comment by mbengtanyi** [comment]
[Instances of excellent faqs](https://drive.google.com/open?id=13ADT-RDema7mcq8ubkY5F9NdmtkbNxBt)

**Comment by Ledicodes** [comment]
1. [Vimeo](vimeo.zendesk.com/hc/en-us)

**Comment by Ledicodes** [comment]
1. [Vimeo](vimeo.zendesk.com/hc/en-us): The layout of Vimeo FAQ page is quite impressive, there is also a large search bar at the header which makes navigation through the FAQs really easy. 
2. [Spotify](support.sportify.com/uk): This FAQ is simple and quite organized, easy to go through each FAQ topic as it does not only answer the question of what but also the how of a frequently asked question. With the presence of a step by step tutorial with screenshots, which makes it an effective way of asking a frequently asked question.
3. [BBC](bc.co.uk/accessibilty): This isn't just a FAQ written in plain text, but it is quite visually driven and it gets you sticking around looking through all the help topics.
4. [Baskin Robbins](https://www.baskinrobbins.com/en/faqs): The bold text on the FAQs main heading makes it quite appealing to the eyes, and a great comparison to BBC's icons. I like the fact that it uses drop downs, it helps the questions not to be clustered.
5. [Vbulletin](vbulletin.com/en/faq): This FAQ topic is organized in sections with plus icons for drop downs. A point to note here is that even with the enormous FAQ it doesn't s still overwhelm the user, as each section has a stand-out colored heading.   
6. [LinkedIn](linkedin.com/help/linkedin): Everything here is great from the layout to the drop downs on the left and the way each FAQ opens up, you get to stay on a particular answer, unless you click another to read which is also a drop down. This really minimizes the length of the text on the page.
7. [Netflix](help.netflix.com): Yet another simple and easy to use FAQ, main heading with sub-headings in drop down makes it clean and straight to the point, the bold headings direct you to the questions.     
8. [Mailchimp](mailchimp.com/help): A great navigation, clear and straight to the point. When you hover over a particular section the others become blur to enable you focus on that particular one which happens to be a nice concept.
9. [Yahoo](help.yahoo.com): This FAQ has a left sidebar to help you browse by topic  instead of searching through a large list of frequently asked questions.
10. [Envato](help.market.envato.com/hc/en-us): The design and it's simplicity is quite awesome, the image for each question stands out quite nice.

Using drop downs for FAQs is my all time favorite and i believe it's a nice choice when making a FAQ page as it enables a lot of text without  causing the page to be crowded with.

**Comment by thelittleveggiekorean** [comment]
1. https://www.revolut.com/help 

: They organised questions in 6 groups with an icon so that users can easily find where to find their answers.  And I like their search bar that shows relative questions down below with the keyword which user is typing 

2. https://help.instagram.com/

: Instagram showed me what does ‘Simpler is better’ Once you click the question on the left side, it showed more specified questions (previous question disappeared) and you can keep going through more specific questions by clicking them. And lastly you will reach accordion style QnA. I think it helps users to concentrate on what they want to know since the other categories disappear. 

3. https://customercare.hyundai.com.au/hc/en-us

: Their faq has ‘Popular Question’ button on top of the general questions. It helps users to find their answers quickly. But in the case that users questions is not included in the popular questions, even if they have the search bar on top,  I think the general questions need to group so that users can find the answer and linked questions users possibly have.

4. https://help.barclaycard.co.uk/brochure/

: Their faq page has few necessary function like search bar, accordion menu on the left, and drop down menu to look for related topic. I don’t think their design is good but since they separate the questions as few pages users wouldn’t be overwhelmed by too long question list at one page 

5. https://cs.kakao.com/
: kakaotalk is like Korean whatsapp. They show the icon button first for users to find the related topic of their question. And it linked to the faq page which is well organised and very simple and easy to use. Since they are mobile based company they have a button for android and iPhone version of each answer. And I thought maybe it can be applied to the language (EN / FR)


Hi! @mmoreshead My name is Chohee and I found few good examples which are designed very simple and have helpful function for users :) I think that good faq page doesn’t need to be necessaily very cool but need to point out the questions cleary. I really like the idea of instagram that meke comprehensive topics disappear and moves on to the more specific topic :)

**Comment by Rubaaw** [comment]
1. [Whatsapp](https://faq.whatsapp.com/):
I like this FAQs so much; the green color scheme is amazing and relaxing, easy to navigate, well divided to sections and categories, there’s a clear search bar at the top, the answer is shown in a simple and clear way.
2. [Royal Jordanian](https://rj.com/en/unused-items/learn-more/faq)
The categories are organized through a drop-down menu, choosing the desired topic will show all the questions related to it, the answers use accordion / expandable functionality for a more effective experience and to support quick access to information without needing to scroll and scroll.
3. [Pinterest](https://help.pinterest.com/)
The page has a stylish style, easy to navigate, search bar at the top to easily search the question or related keywords to save time, well categorized, the answers go with detailed and easy to follow descriptions, with a contact form at the end of each answer for more information or help.
4. [Duolingo](https://support.duolingo.com/)
Again, with the soothing, relaxing blue scheme, a clear search bar at the top of the page that allows you to type the question. Then a link to know more about Duolingo, with all related questions about it. categories with questions, and the answer is really detailed with helpful screenshots, along next to the questions related articles tab, at the end of the faq , if you didn’t find your questions, you have two options either to ask the community or submit a bug report.
5. [Etsy](https://help.etsy.com/)
Straightforward, well organized FAQ page, starting with searching section, followed by featured articles in each category. When you choose an article, you can access another topic which are displayed on the left-hand column. at the end there are other ways to communicate if you didn’t find your answer.
6. [Pocket](https://help.getpocket.com/)
Clean and simple to use, provide access to the most popular articles, with search bar at the top. After choosing a question, the answer is displayed in a simple, detailed description, with search button at the left hand, and the other topics, in the end of each page there is the last updated date to the right and a contact form for Pocket Support to the left.
7. [Uber](https://help.uber.com/)
Another great example of a well-organized FAQ page with nice personalization, easy to use search functionality, below are the categories organized and divided into columns, when viewing a question, the answer is shown in the same great scheme.
8. [Vimeo](https://vimeo.zendesk.com/)
Highly organized FAQ, with the ability to search using the search bar at the top, reading the featured articles, or browsing through the different categories that has a hover option displaying the topics.
At the end of each question, there is a was this article helpful with yes or no options, and related articles at the bottom of the page.
9. [Netflix](https://help.netflix.com/)
Well organized format, at the top section is the search feature to help users find the answers faster, in the middle are the question categories with noticeable headlines, so that you can easily jump to the section you’re asking for, while the bottom is other ways to contact them by calling them or starting a live chat.
10. [Soundcloud](https://help.soundcloud.com/)
Attractive, user friendly layout with blocks displayed in beautiful way, a simple use of cool orange and black icons which is the brand colors, along with categorized sections. you have several options to search on the FAQ page. You can scroll through topics and select the one that best fits your question or you can search your question in the search bar. And there are links on the right side for the promoted articles.

**Comment by mmoreshead** [comment]
Thanks for all these, everyone! The best way to make a good FAQ is to look at other good examples - this kind of research is important!

@Ledicodes many of your links don't work :(

**Comment by Ledicodes** [comment]
That was quite a mistake @mmoreshead they work now

**Comment by kgodey** [comment]
Thank you everyone! I don't have a lot of specific feedback but your research will be very useful to you as you write your final application for this project :)

**Comment by moreinob** [comment]
After careful comparison with the current CC FAQ, I would like to mention these ten 

1. Whatsapp 
https://faq.whatsapp.com
It's bright, easy to use and categorized for quick desktop or mobile use. But then, this is an application and often times when people come here, they already know what they are looking for. I don't think this model would work for CC because from the way the questions were structured on the CC FAQ, I am under the impression that the people who visit the page often don't know what they are looking for so they will want to browse the questions with the hope of finding what they want. If it is the case then 
This won't help them easily find what they are looking for 

2. YouTube
https://support.google.com/youtube#topic=9257498
It's a simple to use FAQ and provides access to the most commonly asked help topics.  It may not be a good model for the CC FAQ but I think having access to the most commonly used FAQ somewhere on the page would help save time for those looking for solutions to similar peoblems

3. Dropbox
https://help.dropbox.com
It brings fun to FAQ and encourages user to experience the site through self discovery. I think this is a good model for a page where people already know what they want. 

4. Twitter 
https://help.twitter.com/en/new-user-faq
Twitter is simple and has almost the same format as the present CC page. The answers to the questions are given in the form of a drop-down menu. This model would work if the answer to the questions are brief and straight to the point. Where a more detailed explanation is needed, this wouldn't work because it would be too cumbersome.

5. Shopify
https://www.shopify.com/faq
The page is very simple and doesn't require a search bar. I like this page but maybe for a brief FAQ within an already existing page. If there is a page within the CC site that has so much information, this model can be used in a column in the page to help people find what they want quickly. 

For 6-10, they are models that can accommodate many questions. They are stylish and tabbed. I would go for any of these since the current CC FAQ page has a lot of questions. Maybe also add proper links to the pages they need to visit after getting the answers they require

6. Pinterest
https://help.pinterest.com/en
It is simple and clearly prioritized. 

7. Microsoft 
https://help.pinterest.com/en
It has a drop down menu that reveals a list of questions. Here questions can be categorized neatly and it will save slot of time. 

8. Mint 
https://help.mint.com
The questions are clear and straight to the point. I like the bold headers used for categorizing the questions. It's very similar to the current CC FAQ though because of the way it's written it's not overwhelming 

9. Buffer 
https://faq.buffer.com
This page has a basic design and instead of the questions appearing on the first page, it is categorized. When a user clicks on any category, it takes them to a different page. This can be useful as there won't be too much information in one place

10. Wikipedia 
https://en.m.wikipedia.org/wiki/Wikipedia:FAQ/Index
The questions are indexed. It is formatted in the same way their article is. There is also a search page. I like the way they categorized the questions into general, specific and similar FAQ.

**Comment by chidexebere** [comment]
My selection of excellent instances of FAQs are based  majorly on the following:

A. Every FAQ should have a search bar where users can easily look up questions and get answers immediately. I feel this is the most important criterion. 

B. Users do not have to scroll multiple times to read through search results. Most of these instances used an accordion.

C. The results or answers the users get from their searches should be in a friendly, itemized and easily readable format.

In no particular order, my excellent instances of FAQs includes:

1. Youtube (https://support.google.com/youtube)

2. Microsoft (https://www.microsoft.com/en-gb/software-download/faq)

3. WhatsApp (https://faq.whatsapp.com/)

4. Twitter (https://help.twitter.com/)

5. Pinterest(https://help.pinterest.com/en#)

6. Udacity (https://udacity.zendesk.com/hc/en-us)

7. Twilio (https://support.twilio.com/hc/en-us)

8. Netflix (https://help.netflix.com/en/)

9. Medium (https://help.medium.com/hc/en-us/articles/360009297694-Frequently-asked-questions-about-distribution-on-Medium)

10. Dropbox (https://help.dropbox.com/)

**Comment by annatuma** [comment]
Thanks @moreinob and @chidexebere for your research. We're looking forward to seeing this research referenced in the final project application.

**Comment by GettyOrawo** [comment]
I chose my Best FAQ instances bearing in mind an interface that I feel happy interacting with. Whenever you are stuck and need to single out one question from a million FAQs it should't be another hurdle to search through the Qs. The following FAQ instances have displayed simplicity at its best while still spouting helpful information.

* **YouTube** 
Youtube's FAQ page displays the questions and answers in a sectional drop down kind of structure where details are revealed when a section is clicked. Notice the search bar. This is usually very helpful.

![youtube](https://user-images.githubusercontent.com/17080976/67677930-6071eb80-f996-11e9-92d8-acfca91aecb1.gif)

* **WhatsApp**
WhatsApp mimics almost a similar structure to youtube but brighter. Having User interface that attracts also plays a huge role in helping one gain interest in other sections of the FAQs apart from the single issue he/she/they are looking for.

![whatsapp](https://user-images.githubusercontent.com/17080976/67678124-e3934180-f996-11e9-8437-c9ca183506f7.gif)

* **Amazon Web Services (AWS)**
AWS is another good example of excellent FAQs. I love how they've placed them in a Q&A kind of format. It's simple, detailed and very interactive. The only downside to this one is a missing search bar.

![AWS](https://user-images.githubusercontent.com/17080976/67678279-4684d880-f997-11e9-9220-ec174919971d.gif)

* **Pinterest**
Pinterest FAQs are divided into subsections. When you click on these they take you to the FAQs that are relative to the subsection headline. With each click, this narrows down the search results for any user to a context they are interested in. Awesome!

![pinterest](https://user-images.githubusercontent.com/17080976/67678578-083be900-f998-11e9-9c07-74317ea1859f.gif)

* **Dropbox**
For few FAQs, Dropbox is the perfect example. It doesn't get any simpler than this. The questions are few so listed vertically. They are highly visible and simple enough for anyone visiting the site to understand

![dropbox](https://user-images.githubusercontent.com/17080976/67678611-1c7fe600-f998-11e9-8a48-8f2c3c37a1a6.gif)


* **BBC**
BBC being a News organization should have a more official looking interface and they pulled it off. The search feature is very helpful when it comes to searching for specific keywords through the FAQs. Notice the use of a single bright color. Rainbows on an FAQ page might be a little too.. playful.

![bbc](https://user-images.githubusercontent.com/17080976/67678500-cd39b580-f997-11e9-9e13-dd027af855cc.gif)

**Comment by mmoreshead** [comment]
Good work, @GettyOrawo!

**Comment by GettyOrawo** [comment]
Thank you. :slightly_smiling_face:

**Comment by kgodey** [comment]
Since the Outreachy application period is over, I'm going to close this issue.
